import T0 from '../templates/about.jsx';
import T1 from '../templates/affiliate-disclosure.jsx';
import T2, { getStaticPaths as paths2 } from '../templates/compare/[slug].jsx';
import T3 from '../templates/compare/index.jsx';
import T4 from '../templates/contact.jsx';
import T5 from '../templates/deals/nordvpn-coupon.jsx';
import T6, { getStaticPaths as paths6 } from '../templates/devices/[slug].jsx';
import T7 from '../templates/devices/index.jsx';
import T8 from '../templates/editorial-policy.jsx';
import T9, { getStaticPaths as paths9 } from '../templates/fix/[slug].jsx';
import T10 from '../templates/fix/index.jsx';
import T11, { getStaticPaths as paths11 } from '../templates/guides/[slug].jsx';
import T12 from '../templates/guides/index.jsx';
import T13 from '../templates/index.jsx';
import T14 from '../templates/learn/index.jsx';
import T15 from '../templates/learn/vpn-on-public-wifi.jsx';
import T16 from '../templates/learn/vpn-vs-https.jsx';
import T17, { getStaticPaths as paths17 } from '../templates/legal/[slug].jsx';
import T18 from '../templates/legal/index.jsx';
import T19 from '../templates/nordvpn/alternatives.jsx';
import T20 from '../templates/pricing/nordvpn-pricing.jsx';
import T21 from '../templates/privacy-policy.jsx';
import T22 from '../templates/reviews/nordvpn.jsx';
import T23 from '../templates/streaming/index.jsx';
import T24, { getStaticPaths as paths24 } from '../templates/use/[slug].jsx';
import T25 from '../templates/use/index.jsx';
import T26, { getStaticPaths as paths26 } from '../templates/vpn/[slug].jsx';
import T27 from '../templates/vpn/index.jsx';
import T28, { getStaticPaths as paths28 } from '../templates/watch/[platform]/[country].jsx';

const routes = new Map();
function add(path, Component, props = {}) {
 if(routes.has(path)) throw new Error('Duplicate existing route: '+path);
 routes.set(path, {Component, props});
}
add("/about", T0);
add("/affiliate-disclosure", T1);
for (const entry of paths2()) add("/compare/[slug]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T2, entry.props);
add("/compare", T3);
add("/contact", T4);
add("/deals/nordvpn-coupon", T5);
for (const entry of paths6()) add("/devices/[slug]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T6, entry.props);
add("/devices", T7);
add("/editorial-policy", T8);
for (const entry of paths9()) add("/fix/[slug]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T9, entry.props);
add("/fix", T10);
for (const entry of paths11()) add("/guides/[slug]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T11, entry.props);
add("/guides", T12);
add("/", T13);
add("/learn", T14);
add("/learn/vpn-on-public-wifi", T15);
add("/learn/vpn-vs-https", T16);
for (const entry of paths17()) add("/legal/[slug]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T17, entry.props);
add("/legal", T18);
add("/nordvpn/alternatives", T19);
add("/pricing/nordvpn-pricing", T20);
add("/privacy-policy", T21);
add("/reviews/nordvpn", T22);
add("/streaming", T23);
for (const entry of paths24()) add("/use/[slug]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T24, entry.props);
add("/use", T25);
for (const entry of paths26()) add("/vpn/[slug]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T26, entry.props);
add("/vpn", T27);
for (const entry of paths28()) add("/watch/[platform]/[country]".replace(/\[([^\]]+)\]/g, (_, key) => entry.params[key]), T28, entry.props);

export default routes;
